/**
 * Vietnamese Crop Database
 * 50+ crops with bilingual (English/Vietnamese) data
 */

export const cropsData = [
  // GRAINS (Ngũ cốc)
  {
    name_en: 'Rice',
    name_vi: 'Lúa',
    scientific_name: 'Oryza sativa',
    category: 'grain',
    growing_season: 'wet',
    typical_growth_days: 120,
    water_requirements: 'high',
    climate_zone: 'tropical, subtropical',
    common_pests: ['brown planthopper', 'stem borer', 'rice bug', 'leaf folder'],
    common_diseases: ['blast', 'bacterial leaf blight', 'sheath blight', 'tungro virus'],
    planting_tips_en: 'Plant in flooded paddies with 20-25cm water depth. Transplant seedlings at 20-25 days old with 15-20cm spacing. Apply basal fertilizer before transplanting. Maintain water level throughout growing season.',
    planting_tips_vi: 'Trồng trong ruộng ngập nước sâu 20-25cm. Cấy mạ khi 20-25 ngày tuổi, khoảng cách 15-20cm. Bón phân nền trước khi cấy. Duy trì mực nước trong suốt vụ.',
    harvest_tips_en: 'Harvest when 80-85% of grains turn golden yellow. Drain field 10-14 days before harvest. Cut at base and allow to dry in field for 2-3 days before threshing.',
    harvest_tips_vi: 'Thu hoạch khi 80-85% hạt chuyển màu vàng. Tháo nước ruộng 10-14 ngày trước thu hoạch. Cắt gốc và phơi ngoài đồng 2-3 ngày trước khi đập.'
  },
  {
    name_en: 'Corn',
    name_vi: 'Ngô',
    scientific_name: 'Zea mays',
    category: 'grain',
    growing_season: 'year_round',
    typical_growth_days: 90,
    water_requirements: 'medium',
    climate_zone: 'tropical, temperate',
    common_pests: ['corn borer', 'armyworm', 'aphids', 'corn earworm'],
    common_diseases: ['leaf blight', 'rust', 'downy mildew', 'stalk rot'],
    planting_tips_en: 'Plant seeds 3-5cm deep in rows 70-80cm apart. Space plants 20-25cm within rows. Requires well-drained soil. Apply NPK fertilizer at planting and again at knee height.',
    planting_tips_vi: 'Gieo hạt sâu 3-5cm, khoảng cách hàng 70-80cm. Cây cách nhau 20-25cm trong hàng. Cần đất thoát nước tốt. Bón phân NPK khi gieo và khi cây cao ngang đầu gối.',
    harvest_tips_en: 'Harvest when kernels are firm and milky. Husk should be dry and brown. Pick early morning for best quality. Dry to 14% moisture before storage.',
    harvest_tips_vi: 'Thu hoạch khi hạt chắc và có màu sữa. Vỏ ngoài khô và chuyển màu nâu. Hái vào sáng sớm để đảm bảo chất lượng. Phơi đến độ ẩm 14% trước khi cất giữ.'
  },
  {
    name_en: 'Wheat',
    name_vi: 'Lúa mì',
    scientific_name: 'Triticum aestivum',
    category: 'grain',
    growing_season: 'dry',
    typical_growth_days: 120,
    water_requirements: 'medium',
    climate_zone: 'temperate',
    common_pests: ['aphids', 'wheat stem sawfly', 'grasshoppers'],
    common_diseases: ['rust', 'smut', 'septoria', 'fusarium head blight'],
    planting_tips_en: 'Sow in well-prepared seedbed. Optimal soil temperature 10-15°C. Seed depth 3-5cm. Row spacing 15-20cm. Requires cool temperatures during growth.',
    planting_tips_vi: 'Gieo trong luống đất chuẩn bị kỹ. Nhiệt độ đất tối ưu 10-15°C. Độ sâu gieo 3-5cm. Khoảng cách hàng 15-20cm. Cần nhiệt độ mát trong thời gian sinh trưởng.',
    harvest_tips_en: 'Harvest when grain moisture is 13-14%. Grain should be hard when bitten. Cut and windrow, then thresh when fully dry.',
    harvest_tips_vi: 'Thu hoạch khi độ ẩm hạt 13-14%. Hạt phải cứng khi cắn. Cắt và để phơi, sau đó đập khi khô hoàn toàn.'
  },

  // VEGETABLES (Rau củ)
  {
    name_en: 'Tomato',
    name_vi: 'Cà chua',
    scientific_name: 'Solanum lycopersicum',
    category: 'vegetable',
    growing_season: 'year_round',
    typical_growth_days: 75,
    water_requirements: 'medium',
    climate_zone: 'tropical, subtropical, temperate',
    common_pests: ['whitefly', 'aphids', 'tomato hornworm', 'fruit borer'],
    common_diseases: ['early blight', 'late blight', 'bacterial wilt', 'mosaic virus'],
    planting_tips_en: 'Start from seedlings 25-30 days old. Plant in well-drained soil with pH 6.0-6.8. Space 50-60cm apart. Provide support stakes. Mulch to retain moisture.',
    planting_tips_vi: 'Bắt đầu từ cây con 25-30 ngày tuổi. Trồng trong đất thoát nước tốt, pH 6.0-6.8. Khoảng cách 50-60cm. Dùng cọc chống đỡ. Phủ rơm giữ ẩm.',
    harvest_tips_en: 'Pick when fruit is fully colored but still firm. Harvest every 2-3 days during peak season. Handle gently to avoid bruising. Store at room temperature.',
    harvest_tips_vi: 'Hái khi quả đã chuyển màu hoàn toàn nhưng vẫn còn chắc. Thu hoạch mỗi 2-3 ngày trong mùa cao điểm. Xử lý nhẹ nhàng tránh dập. Bảo quản ở nhiệt độ phòng.'
  },
  {
    name_en: 'Cabbage',
    name_vi: 'Bắp cải',
    scientific_name: 'Brassica oleracea var. capitata',
    category: 'vegetable',
    growing_season: 'dry',
    typical_growth_days: 70,
    water_requirements: 'high',
    climate_zone: 'temperate, subtropical',
    common_pests: ['cabbage worm', 'aphids', 'diamondback moth', 'cutworm'],
    common_diseases: ['black rot', 'clubroot', 'downy mildew'],
    planting_tips_en: 'Transplant seedlings at 3-4 weeks old. Space 40-50cm apart in rows 60cm apart. Prefers cool weather. Keep soil consistently moist. Apply nitrogen fertilizer.',
    planting_tips_vi: 'Cấy cây con 3-4 tuần tuổi. Khoảng cách 40-50cm, hàng cách nhau 60cm. Thích thời tiết mát. Giữ đất ẩm đều đặn. Bón phân đạm.',
    harvest_tips_en: 'Harvest when heads are firm and tight. Cut at base leaving outer leaves. Can tolerate light frost. Best harvested in morning.',
    harvest_tips_vi: 'Thu hoạch khi búp chắc và chặt. Cắt ở gốc, để lại lá ngoài. Chịu được sương giá nhẹ. Tốt nhất là thu hoạch vào buổi sáng.'
  },
  {
    name_en: 'Lettuce',
    name_vi: 'Xà lách',
    scientific_name: 'Lactuca sativa',
    category: 'vegetable',
    growing_season: 'dry',
    typical_growth_days: 45,
    water_requirements: 'medium',
    climate_zone: 'temperate, subtropical',
    common_pests: ['aphids', 'slugs', 'leaf miners'],
    common_diseases: ['downy mildew', 'tip burn', 'bottom rot'],
    planting_tips_en: 'Direct seed or transplant. Prefers cool temperatures 15-20°C. Space 25-30cm apart. Provide shade in hot weather. Water regularly to prevent bitterness.',
    planting_tips_vi: 'Gieo trực tiếp hoặc cấy. Thích nhiệt độ mát 15-20°C. Khoảng cách 25-30cm. Che bóng khi thời tiết nóng. Tưới đều đặn để tránh đắng.',
    harvest_tips_en: 'Harvest whole head by cutting at base, or pick outer leaves continuously. Best harvested in early morning. Use within 2-3 days for best quality.',
    harvest_tips_vi: 'Thu hoạch cả búp bằng cách cắt ở gốc, hoặc hái lá ngoài liên tục. Tốt nhất thu hoạch vào sáng sớm. Sử dụng trong 2-3 ngày để đảm bảo chất lượng.'
  },
  {
    name_en: 'Cucumber',
    name_vi: 'Dưa chuột',
    scientific_name: 'Cucumis sativus',
    category: 'vegetable',
    growing_season: 'year_round',
    typical_growth_days: 55,
    water_requirements: 'high',
    climate_zone: 'tropical, subtropical',
    common_pests: ['cucumber beetle', 'aphids', 'whitefly', 'spider mites'],
    common_diseases: ['powdery mildew', 'downy mildew', 'bacterial wilt', 'mosaic virus'],
    planting_tips_en: 'Plant seeds 2cm deep in hills or rows. Space plants 30-40cm apart. Provide trellis for vertical growth. Mulch to conserve moisture. Regular watering essential.',
    planting_tips_vi: 'Gieo hạt sâu 2cm theo đống hoặc hàng. Khoảng cách 30-40cm. Dựng giàn cho cây leo. Phủ rơm giữ ẩm. Tưới nước đều đặn rất quan trọng.',
    harvest_tips_en: 'Pick when fruit reaches desired size, usually 15-20cm. Harvest daily during peak production. Cut stem with knife. Refrigerate immediately.',
    harvest_tips_vi: 'Hái khi quả đạt kích thước mong muốn, thường 15-20cm. Thu hoạch hàng ngày trong mùa cao điểm. Cắt cuống bằng dao. Bảo quản lạnh ngay.'
  },
  {
    name_en: 'Chili Pepper',
    name_vi: 'Ớt',
    scientific_name: 'Capsicum annuum',
    category: 'vegetable',
    growing_season: 'year_round',
    typical_growth_days: 80,
    water_requirements: 'medium',
    climate_zone: 'tropical, subtropical',
    common_pests: ['aphids', 'thrips', 'fruit borer', 'whitefly'],
    common_diseases: ['anthracnose', 'bacterial spot', 'mosaic virus'],
    planting_tips_en: 'Transplant seedlings at 4-6 weeks old. Space 40-50cm apart. Prefers warm weather 20-30°C. Stake plants for support. Avoid overwatering.',
    planting_tips_vi: 'Cấy cây con 4-6 tuần tuổi. Khoảng cách 40-50cm. Thích thời tiết ấm 20-30°C. Dựng cọc chống đỡ. Tránh tưới quá nhiều nước.',
    harvest_tips_en: 'Pick green or wait for full color maturity. Use scissors to cut stem. Harvest regularly to encourage production. Can be dried or frozen for storage.',
    harvest_tips_vi: 'Hái khi còn xanh hoặc chờ chín màu hoàn toàn. Dùng kéo cắt cuống. Thu hoạch đều đặn để kích thích sinh trưởng. Có thể phơi khô hoặc đông lạnh bảo quản.'
  },
  {
    name_en: 'Eggplant',
    name_vi: 'Cà tím',
    scientific_name: 'Solanum melongena',
    category: 'vegetable',
    growing_season: 'year_round',
    typical_growth_days: 70,
    water_requirements: 'medium',
    climate_zone: 'tropical, subtropical',
    common_pests: ['fruit borer', 'aphids', 'whitefly', 'spider mites'],
    common_diseases: ['bacterial wilt', 'phomopsis blight', 'mosaic virus'],
    planting_tips_en: 'Transplant 6-8 week old seedlings. Space 50-60cm apart. Requires warm soil and air. Mulch and provide consistent moisture. Stake tall varieties.',
    planting_tips_vi: 'Cấy cây con 6-8 tuần tuổi. Khoảng cách 50-60cm. Cần đất và không khí ấm. Phủ rơm và tưới đều. Dựng cọc cho giống cao.',
    harvest_tips_en: 'Pick when fruit is glossy and firm, before seeds harden. Cut stem with pruners. Harvest every 2-3 days. Store in cool place.',
    harvest_tips_vi: 'Hái khi quả bóng và chắc, trước khi hạt cứng. Cắt cuống bằng kéo. Thu hoạch mỗi 2-3 ngày. Bảo quản ở nơi mát.'
  },
  {
    name_en: 'Carrot',
    name_vi: 'Cà rốt',
    scientific_name: 'Daucus carota',
    category: 'vegetable',
    growing_season: 'dry',
    typical_growth_days: 75,
    water_requirements: 'medium',
    climate_zone: 'temperate, subtropical',
    common_pests: ['carrot fly', 'aphids', 'wireworms'],
    common_diseases: ['leaf blight', 'root rot', 'powdery mildew'],
    planting_tips_en: 'Direct sow seeds 1-2cm deep in loose, well-drained soil. Thin seedlings to 5-7cm apart. Prefers cool weather. Keep soil moist but not waterlogged.',
    planting_tips_vi: 'Gieo trực tiếp hạt sâu 1-2cm trong đất tơi xốp, thoát nước tốt. Tỉa cây con cách nhau 5-7cm. Thích thời tiết mát. Giữ đất ẩm nhưng không úng.',
    harvest_tips_en: 'Pull when roots reach desired size, usually 2-3cm diameter. Loosen soil before pulling. Can leave in ground in cool climates. Remove tops before storage.',
    harvest_tips_vi: 'Nhổ khi củ đạt kích thước mong muốn, thường đường kính 2-3cm. Xới đất trước khi nhổ. Có thể để trong đất ở vùng khí hậu mát. Cắt bỏ lá trước khi bảo quản.'
  },
  {
    name_en: 'Bean (Green)',
    name_vi: 'Đậu cove',
    scientific_name: 'Phaseolus vulgaris',
    category: 'vegetable',
    growing_season: 'year_round',
    typical_growth_days: 55,
    water_requirements: 'medium',
    climate_zone: 'tropical, subtropical, temperate',
    common_pests: ['bean beetle', 'aphids', 'pod borer'],
    common_diseases: ['rust', 'anthracnose', 'mosaic virus'],
    planting_tips_en: 'Direct sow seeds 3-4cm deep. Bush types: 10-15cm apart. Pole types: 15-20cm apart with support. Inoculate with rhizobium. Avoid wet foliage.',
    planting_tips_vi: 'Gieo trực tiếp hạt sâu 3-4cm. Giống bụi: cách 10-15cm. Giống leo: cách 15-20cm và dựng giàn. Ủ vi khuẩn rhizobium. Tránh ướt lá.',
    harvest_tips_en: 'Pick pods when young and tender, before beans bulge. Harvest every 2-3 days. Best picked in morning. Refrigerate immediately for best quality.',
    harvest_tips_vi: 'Hái quả khi còn non và mềm, trước khi hạt phồng. Thu hoạch mỗi 2-3 ngày. Tốt nhất hái vào buổi sáng. Bảo quản lạnh ngay để đảm bảo chất lượng.'
  },

  // FRUITS (Trái cây)
  {
    name_en: 'Mango',
    name_vi: 'Xoài',
    scientific_name: 'Mangifera indica',
    category: 'fruit',
    growing_season: 'year_round',
    typical_growth_days: 120,
    water_requirements: 'medium',
    climate_zone: 'tropical',
    common_pests: ['mango hopper', 'fruit fly', 'mealybug', 'scale insects'],
    common_diseases: ['anthracnose', 'powdery mildew', 'bacterial canker'],
    planting_tips_en: 'Plant grafted trees 8-10m apart. Requires full sun and well-drained soil. Water regularly during fruit development. Apply balanced fertilizer 3-4 times per year.',
    planting_tips_vi: 'Trồng cây ghép cách nhau 8-10m. Cần đầy đủ ánh sáng và đất thoát nước tốt. Tưới đều đặn khi quả đang phát triển. Bón phân cân đối 3-4 lần/năm.',
    harvest_tips_en: 'Harvest when fruit develops characteristic aroma and color. Cut stem leaving 10cm stalk. Allow to ripen at room temperature. Peak season varies by variety.',
    harvest_tips_vi: 'Thu hoạch khi quả có mùi thơm đặc trưng và chuyển màu. Cắt để lại cuống 10cm. Để chín ở nhiệt độ phòng. Mùa vụ cao điểm tùy giống.'
  },
  {
    name_en: 'Dragon Fruit',
    name_vi: 'Thanh long',
    scientific_name: 'Hylocereus undatus',
    category: 'fruit',
    growing_season: 'year_round',
    typical_growth_days: 30,
    water_requirements: 'low',
    climate_zone: 'tropical, subtropical',
    common_pests: ['ants', 'mealybug', 'scale insects', 'fruit fly'],
    common_diseases: ['stem rot', 'anthracnose', 'brown spot'],
    planting_tips_en: 'Plant cuttings 50-60cm deep with support posts 2-2.5m apart. Requires well-drained soil. Prune regularly to promote flowering. Apply organic fertilizer monthly.',
    planting_tips_vi: 'Trồng cành giâm sâu 50-60cm với cọc chống đỡ cách 2-2.5m. Cần đất thoát nước tốt. Tỉa cành thường xuyên để kích thích ra hoa. Bón phân hữu cơ hàng tháng.',
    harvest_tips_en: 'Pick 30-35 days after flowering when skin color changes. Fruit should be slightly soft. Use clippers to cut. Can fruit multiple times per year.',
    harvest_tips_vi: 'Hái sau 30-35 ngày kể từ khi ra hoa khi vỏ chuyển màu. Quả hơi mềm. Dùng kéo cắt. Có thể ra quả nhiều lần trong năm.'
  },
  {
    name_en: 'Banana',
    name_vi: 'Chuối',
    scientific_name: 'Musa spp.',
    category: 'fruit',
    growing_season: 'year_round',
    typical_growth_days: 270,
    water_requirements: 'high',
    climate_zone: 'tropical',
    common_pests: ['banana weevil', 'nematodes', 'aphids'],
    common_diseases: ['panama disease', 'sigatoka', 'bunchy top virus'],
    planting_tips_en: 'Plant suckers 2-3m apart in rich, well-drained soil. Requires constant moisture and high humidity. Mulch heavily. Apply high-potassium fertilizer regularly.',
    planting_tips_vi: 'Trồng chồi cách nhau 2-3m trong đất giàu dinh dưỡng, thoát nước tốt. Cần độ ẩm cao và tưới thường xuyên. Phủ rơm dày. Bón phân giàu kali thường xuyên.',
    harvest_tips_en: 'Cut bunch when fruit is full but still green. Hang in shaded area to ripen. Remove flower end after harvesting. Plant produces one bunch then dies.',
    harvest_tips_vi: 'Cắt nải khi quả đầy nhưng vẫn xanh. Treo ở nơi râm để chín. Cắt bỏ phần hoa sau khi thu hoạch. Cây cho một nải rồi chết.'
  },
  {
    name_en: 'Longan',
    name_vi: 'Nhãn',
    scientific_name: 'Dimocarpus longan',
    category: 'fruit',
    growing_season: 'year_round',
    typical_growth_days: 120,
    water_requirements: 'medium',
    climate_zone: 'tropical, subtropical',
    common_pests: ['longan stink bug', 'fruit borer', 'leaf miner'],
    common_diseases: ['downy mildew', 'algal spot', 'fruit rot'],
    planting_tips_en: 'Plant grafted trees 6-8m apart. Needs cool dry period for flowering. Provide adequate water during fruit development. Prune after harvest.',
    planting_tips_vi: 'Trồng cây ghép cách nhau 6-8m. Cần thời kỳ khô mát để ra hoa. Tưới đủ nước khi quả đang phát triển. Tỉa cành sau thu hoạch.',
    harvest_tips_en: 'Harvest clusters when fruit is light brown and sweet. Cut whole panicle. Can store 2-3 weeks refrigerated. Peak season July-August.',
    harvest_tips_vi: 'Thu hoạch chùm khi quả chuyển màu nâu nhạt và ngọt. Cắt cả chùm. Có thể bảo quản 2-3 tuần trong tủ lạnh. Mùa cao điểm tháng 7-8.'
  },
  {
    name_en: 'Papaya',
    name_vi: 'Đu đủ',
    scientific_name: 'Carica papaya',
    category: 'fruit',
    growing_season: 'year_round',
    typical_growth_days: 270,
    water_requirements: 'medium',
    climate_zone: 'tropical',
    common_pests: ['fruit fly', 'aphids', 'mites', 'whitefly'],
    common_diseases: ['papaya ringspot virus', 'anthracnose', 'powdery mildew'],
    planting_tips_en: 'Plant 2-3 seeds per hole, 2-3m apart. Select one strong seedling. Requires full sun and well-drained soil. Apply balanced fertilizer monthly.',
    planting_tips_vi: 'Gieo 2-3 hạt mỗi hố, cách nhau 2-3m. Chọn một cây khỏe. Cần đầy đủ ánh sáng và đất thoát nước tốt. Bón phân cân đối hàng tháng.',
    harvest_tips_en: 'Harvest when fruit shows yellow color. Pick when slightly soft. Fruit ripens year-round. Can produce for 3-4 years.',
    harvest_tips_vi: 'Thu hoạch khi quả chuyển màu vàng. Hái khi hơi mềm. Quả chín quanh năm. Có thể cho quả 3-4 năm.'
  },
  {
    name_en: 'Watermelon',
    name_vi: 'Dưa hấu',
    scientific_name: 'Citrullus lanatus',
    category: 'fruit',
    growing_season: 'dry',
    typical_growth_days: 80,
    water_requirements: 'medium',
    climate_zone: 'tropical, subtropical',
    common_pests: ['aphids', 'fruit fly', 'cucumber beetle', 'whitefly'],
    common_diseases: ['fusarium wilt', 'anthracnose', 'gummy stem blight'],
    planting_tips_en: 'Plant seeds 2-3cm deep in hills 2-3m apart. Requires warm soil and full sun. Mulch to retain moisture. Reduce water as fruit matures.',
    planting_tips_vi: 'Gieo hạt sâu 2-3cm theo đống cách nhau 2-3m. Cần đất ấm và đầy đủ ánh sáng. Phủ rơm giữ ẩm. Giảm nước khi quả gần chín.',
    harvest_tips_en: 'Test ripeness by thumping (hollow sound) and checking tendril near fruit (brown when ripe). Cut stem leaving 5cm attached. Peak season March-May.',
    harvest_tips_vi: 'Kiểm tra chín bằng cách gõ (âm thanh rỗng) và xem tua cuốn gần quả (nâu khi chín). Cắt để lại cuống 5cm. Mùa cao điểm tháng 3-5.'
  },

  // CASH CROPS (Cây công nghiệp)
  {
    name_en: 'Coffee',
    name_vi: 'Cà phê',
    scientific_name: 'Coffea arabica / Coffea canephora',
    category: 'cash_crop',
    growing_season: 'year_round',
    typical_growth_days: 270,
    water_requirements: 'high',
    climate_zone: 'tropical, subtropical',
    common_pests: ['coffee berry borer', 'leaf miner', 'scale insects', 'mealybug'],
    common_diseases: ['coffee rust', 'berry disease', 'root rot'],
    planting_tips_en: 'Plant seedlings 2-3m apart with shade trees. Requires altitude 600-1200m for Arabica. Keep soil moist. Apply organic fertilizer 3-4 times yearly. Prune to maintain shape.',
    planting_tips_vi: 'Trồng cây con cách nhau 2-3m có cây che bóng. Cần độ cao 600-1200m cho Arabica. Giữ đất ẩm. Bón phân hữu cơ 3-4 lần/năm. Tỉa cành giữ dáng.',
    harvest_tips_en: 'Pick only ripe red cherries selectively. Multiple pickings per season. Process within 24 hours. Dry to 11-12% moisture. Main harvest October-December.',
    harvest_tips_vi: 'Hái chọn lọc chỉ quả chín đỏ. Nhiều lần hái trong mùa. Chế biến trong vòng 24 giờ. Phơi khô đến độ ẩm 11-12%. Vụ chính tháng 10-12.'
  },
  {
    name_en: 'Rubber',
    name_vi: 'Cao su',
    scientific_name: 'Hevea brasiliensis',
    category: 'cash_crop',
    growing_season: 'year_round',
    typical_growth_days: 2190,
    water_requirements: 'high',
    climate_zone: 'tropical',
    common_pests: ['pink disease', 'termites', 'leaf-eating caterpillars'],
    common_diseases: ['white root disease', 'black stripe', 'powdery mildew'],
    planting_tips_en: 'Plant budded stumps 6-7m apart. Requires 2000mm+ annual rainfall. Clear weeds regularly. Apply fertilizer based on soil test. Can tap after 6-7 years.',
    planting_tips_vi: 'Trồng cây ghép mắt cách nhau 6-7m. Cần lượng mưa 2000mm+/năm. Làm cỏ thường xuyên. Bón phân theo kết quả phân tích đất. Có thể khai thác sau 6-7 năm.',
    harvest_tips_en: 'Tap early morning at 1/3 bark depth. Rest trees during leaf fall period. Apply stimulants carefully. Average productive life 25-30 years.',
    harvest_tips_vi: 'Cạo mủ sáng sớm ở độ sâu 1/3 vỏ. Nghỉ cạo khi rụng lá. Dùng kích thích cẩn thận. Tuổi khai thác trung bình 25-30 năm.'
  },
  {
    name_en: 'Tea',
    name_vi: 'Chè',
    scientific_name: 'Camellia sinensis',
    category: 'cash_crop',
    growing_season: 'year_round',
    typical_growth_days: 1095,
    water_requirements: 'high',
    climate_zone: 'subtropical',
    common_pests: ['tea mosquito bug', 'red spider mite', 'thrips'],
    common_diseases: ['blister blight', 'root rot', 'grey blight'],
    planting_tips_en: 'Plant cuttings 1.2m apart in acidic soil pH 4.5-5.5. Requires altitude 1000-2000m and cool climate. Prune to maintain bush at 0.6-1m. First plucking after 3 years.',
    planting_tips_vi: 'Trồng cành giâm cách nhau 1.2m trong đất chua pH 4.5-5.5. Cần độ cao 1000-2000m và khí hậu mát. Tỉa giữ bụi cao 0.6-1m. Hái lần đầu sau 3 năm.',
    harvest_tips_en: 'Pluck 2 leaves and a bud every 7-10 days. Hand plucking for quality tea. Process immediately after plucking. Productive for 50+ years with proper care.',
    harvest_tips_vi: 'Hái 2 lá 1 tôm mỗi 7-10 ngày. Hái tay cho chè chất lượng cao. Chế biến ngay sau khi hái. Cho sản phẩm trên 50 năm nếu chăm sóc tốt.'
  },
  {
    name_en: 'Black Pepper',
    name_vi: 'Tiêu đen',
    scientific_name: 'Piper nigrum',
    category: 'cash_crop',
    growing_season: 'year_round',
    typical_growth_days: 1095,
    water_requirements: 'high',
    climate_zone: 'tropical',
    common_pests: ['pepper beetle', 'scale insects', 'nematodes'],
    common_diseases: ['foot rot', 'anthracnose', 'leaf spot'],
    planting_tips_en: 'Plant rooted cuttings with support poles 2.5-3m apart. Requires shade in early years. Mulch heavily. Apply organic manure and balanced fertilizer. Can produce after 3 years.',
    planting_tips_vi: 'Trồng cành giâm có rễ với cột chống đỡ cách 2.5-3m. Cần bóng mát khi còn nhỏ. Phủ rơm dày. Bón phân hữu cơ và phân cân đối. Có thể cho quả sau 3 năm.',
    harvest_tips_en: 'Harvest when berries turn red (for black pepper) or fully ripe (for white pepper). Dry in sun until dark and wrinkled. Can produce for 20+ years.',
    harvest_tips_vi: 'Thu hoạch khi quả chuyển đỏ (tiêu đen) hoặc chín hoàn toàn (tiêu trắng). Phơi khô đến khi đen và nhăn. Có thể cho quả trên 20 năm.'
  },
  {
    name_en: 'Sugarcane',
    name_vi: 'Mía',
    scientific_name: 'Saccharum officinarum',
    category: 'cash_crop',
    growing_season: 'year_round',
    typical_growth_days: 360,
    water_requirements: 'high',
    climate_zone: 'tropical, subtropical',
    common_pests: ['shoot borer', 'white grub', 'termites', 'aphids'],
    common_diseases: ['red rot', 'smut', 'mosaic', 'wilt'],
    planting_tips_en: 'Plant cane sets with 2-3 buds in furrows 90-120cm apart. Requires fertile, well-drained soil. Irrigate during dry periods. Apply nitrogen fertilizer in stages.',
    planting_tips_vi: 'Trồng đoạn mía có 2-3 mắt trong rãnh cách 90-120cm. Cần đất màu mỡ, thoát nước tốt. Tưới khi khô hạn. Bón phân đạm theo từng giai đoạn.',
    harvest_tips_en: 'Harvest at 12-18 months when leaves turn yellow and cane is hard. Cut at ground level. Process within 24 hours for best sugar recovery.',
    harvest_tips_vi: 'Thu hoạch sau 12-18 tháng khi lá vàng và cây cứng. Chặt sát mặt đất. Chế biến trong vòng 24 giờ để thu hồi đường tốt nhất.'
  },
  {
    name_en: 'Cashew',
    name_vi: 'Điều',
    scientific_name: 'Anacardium occidentale',
    category: 'cash_crop',
    growing_season: 'year_round',
    typical_growth_days: 1095,
    water_requirements: 'low',
    climate_zone: 'tropical',
    common_pests: ['tea mosquito bug', 'stem borer', 'leaf miner'],
    common_diseases: ['dieback', 'anthracnose', 'powdery mildew'],
    planting_tips_en: 'Plant grafted seedlings 7-10m apart. Tolerates poor soil but needs good drainage. Water during establishment. Apply organic fertilizer yearly. Can produce after 3 years.',
    planting_tips_vi: 'Trồng cây ghép cách nhau 7-10m. Chịu được đất nghèo nhưng cần thoát nước tốt. Tưới khi còn nhỏ. Bón phân hữu cơ hàng năm. Có thể cho quả sau 3 năm.',
    harvest_tips_en: 'Harvest when apple is fully colored and nut is mature. Collect from ground. Process nuts carefully (caustic shell). Main harvest February-May.',
    harvest_tips_vi: 'Thu hoạch khi táo chuyển màu hoàn toàn và hạt chín. Nhặt từ mặt đất. Chế biến hạt cẩn thận (vỏ ăn da). Vụ chính tháng 2-5.'
  },

  // LEGUMES (Đậu họ đậu)
  {
    name_en: 'Soybean',
    name_vi: 'Đậu nành',
    scientific_name: 'Glycine max',
    category: 'legume',
    growing_season: 'dry',
    typical_growth_days: 100,
    water_requirements: 'medium',
    climate_zone: 'tropical, subtropical, temperate',
    common_pests: ['pod borer', 'aphids', 'bean fly', 'whitefly'],
    common_diseases: ['rust', 'mosaic virus', 'bacterial blight'],
    planting_tips_en: 'Sow seeds 3-4cm deep in rows 40-50cm apart. Inoculate with rhizobium bacteria. Requires well-drained soil. Avoid waterlogging. Light fertilizer needed.',
    planting_tips_vi: 'Gieo hạt sâu 3-4cm, hàng cách nhau 40-50cm. Ủ vi khuẩn rhizobium. Cần đất thoát nước tốt. Tránh úng nước. Ít cần phân bón.',
    harvest_tips_en: 'Harvest when 95% of pods are brown and rattle. Cut plants and dry in field. Thresh when fully dry. Store at 13% moisture.',
    harvest_tips_vi: 'Thu hoạch khi 95% quả chuyển nâu và lạo xạo. Cắt cây và phơi ngoài đồng. Đập khi khô hoàn toàn. Bảo quản ở độ ẩm 13%.'
  },
  {
    name_en: 'Peanut',
    name_vi: 'Đậu phộng',
    scientific_name: 'Arachis hypogaea',
    category: 'legume',
    growing_season: 'dry',
    typical_growth_days: 120,
    water_requirements: 'medium',
    climate_zone: 'tropical, subtropical',
    common_pests: ['aphids', 'thrips', 'termites', 'white grub'],
    common_diseases: ['leaf spot', 'rust', 'collar rot'],
    planting_tips_en: 'Plant seeds 5cm deep in sandy loam soil. Space 15-20cm in rows 30cm apart. Requires calcium. Mound soil around base during flowering.',
    planting_tips_vi: 'Gieo hạt sâu 5cm trong đất thịt pha cát. Khoảng cách 15-20cm, hàng cách 30cm. Cần canxi. Vun gốc khi ra hoa.',
    harvest_tips_en: 'Dig when leaves turn yellow and pods are mature. Cure by drying plants upside down for 2-3 weeks. Shell and dry to 7-9% moisture.',
    harvest_tips_vi: 'Đào khi lá vàng và quả chín. Ủ bằng cách phơi cây úp ngược 2-3 tuần. Bóc vỏ và phơi khô đến độ ẩm 7-9%.'
  },

  // Additional common Vietnamese crops
  {
    name_en: 'Sweet Potato',
    name_vi: 'Khoai lang',
    scientific_name: 'Ipomoea batatas',
    category: 'vegetable',
    growing_season: 'year_round',
    typical_growth_days: 120,
    water_requirements: 'medium',
    climate_zone: 'tropical, subtropical',
    common_pests: ['sweet potato weevil', 'wireworm', 'aphids'],
    common_diseases: ['fusarium wilt', 'black rot', 'leaf spot'],
    planting_tips_en: 'Plant vine cuttings 25-30cm long in ridges 75-90cm apart. Space cuttings 30cm apart. Prefers sandy loam. Minimal fertilizer needed. Mulch to conserve moisture.',
    planting_tips_vi: 'Trồng cành dây dài 25-30cm trên luống cách nhau 75-90cm. Cành cách nhau 30cm. Thích đất thịt pha cát. Ít cần phân bón. Phủ rơm giữ ẩm.',
    harvest_tips_en: 'Dig when vines start yellowing, 90-120 days after planting. Cure in warm humid place for 1 week. Store at 13-15°C. Can be harvested progressively.',
    harvest_tips_vi: 'Đào khi dây bắt đầu vàng, 90-120 ngày sau trồng. Ủ ở nơi ấm ẩm 1 tuần. Bảo quản ở 13-15°C. Có thể thu hoạch dần.'
  },
  {
    name_en: 'Cassava',
    name_vi: 'Sắn',
    scientific_name: 'Manihot esculenta',
    category: 'vegetable',
    growing_season: 'year_round',
    typical_growth_days: 270,
    water_requirements: 'low',
    climate_zone: 'tropical',
    common_pests: ['mealybug', 'mites', 'termites'],
    common_diseases: ['mosaic virus', 'bacterial blight', 'root rot'],
    planting_tips_en: 'Plant stem cuttings 20-25cm long horizontally or at angle. Space 1m x 1m. Very drought tolerant. Minimal care required. Grows on poor soils.',
    planting_tips_vi: 'Trồng cành dài 20-25cm nằm ngang hoặc nghiêng. Khoảng cách 1m x 1m. Rất chịu hạn. Ít cần chăm sóc. Mọc được trên đất nghèo.',
    harvest_tips_en: 'Dig roots 8-12 months after planting. Can leave in ground until needed. Process within 24-48 hours after harvest. Dry chips to 13% moisture.',
    harvest_tips_vi: 'Đào củ sau 8-12 tháng trồng. Có thể để trong đất đến khi cần. Chế biến trong vòng 24-48 giờ sau thu hoạch. Phơi khô lát đến độ ẩm 13%.'
  },
  {
    name_en: 'Taro',
    name_vi: 'Khoai môn',
    scientific_name: 'Colocasia esculenta',
    category: 'vegetable',
    growing_season: 'wet',
    typical_growth_days: 180,
    water_requirements: 'high',
    climate_zone: 'tropical',
    common_pests: ['taro beetle', 'aphids', 'armyworm'],
    common_diseases: ['leaf blight', 'corm rot', 'mosaic virus'],
    planting_tips_en: 'Plant corm sections with bud 10-15cm deep. Space 50-60cm apart. Can grow in flooded or upland conditions. Requires organic-rich soil. Keep consistently moist.',
    planting_tips_vi: 'Trồng đoạn củ có mầm sâu 10-15cm. Khoảng cách 50-60cm. Có thể trồng ngập nước hoặc khô. Cần đất giàu chất hữu cơ. Giữ ẩm đều đặn.',
    harvest_tips_en: 'Harvest 6-9 months after planting when leaves yellow. Dig carefully to avoid damage. Cure in shade for 1-2 days before storage.',
    harvest_tips_vi: 'Thu hoạch sau 6-9 tháng trồng khi lá vàng. Đào cẩn thận tránh làm hỏng. Ủ ở nơi râm 1-2 ngày trước khi cất giữ.'
  },
  {
    name_en: 'Mustard Greens',
    name_vi: 'Cải xanh',
    scientific_name: 'Brassica juncea',
    category: 'vegetable',
    growing_season: 'dry',
    typical_growth_days: 40,
    water_requirements: 'medium',
    climate_zone: 'temperate, subtropical',
    common_pests: ['aphids', 'cabbage worm', 'diamondback moth'],
    common_diseases: ['downy mildew', 'white rust', 'black rot'],
    planting_tips_en: 'Direct sow or transplant seedlings 25-30cm apart. Prefers cool weather. Keep soil consistently moist. Fast growing. Can harvest multiple times.',
    planting_tips_vi: 'Gieo trực tiếp hoặc cấy cây con cách nhau 25-30cm. Thích thời tiết mát. Giữ đất ẩm đều đặn. Sinh trưởng nhanh. Có thể thu hoạch nhiều lần.',
    harvest_tips_en: 'Pick outer leaves when 15-20cm long, or harvest whole plant. Best quality before flowering. Harvest in morning for crispness.',
    harvest_tips_vi: 'Hái lá ngoài khi dài 15-20cm, hoặc thu hoạch cả cây. Chất lượng tốt nhất trước khi ra hoa. Thu hoạch vào buổi sáng để giòn.'
  },
  {
    name_en: 'Water Spinach',
    name_vi: 'Rau muống',
    scientific_name: 'Ipomoea aquatica',
    category: 'vegetable',
    growing_season: 'year_round',
    typical_growth_days: 30,
    water_requirements: 'high',
    climate_zone: 'tropical',
    common_pests: ['aphids', 'leaf miner', 'caterpillars'],
    common_diseases: ['white rust', 'leaf spot'],
    planting_tips_en: 'Plant stem cuttings in wet soil or shallow water. Space 15-20cm apart. Can grow in aquatic or terrestrial conditions. Very fast growing. Minimal care needed.',
    planting_tips_vi: 'Trồng cành trong đất ướt hoặc nước nông. Khoảng cách 15-20cm. Có thể trồng trong nước hoặc đất. Sinh trưởng rất nhanh. Ít cần chăm sóc.',
    harvest_tips_en: 'Cut shoots 20-25 days after planting, leaving 5cm for regrowth. Can harvest every 10-15 days. Best harvested in morning.',
    harvest_tips_vi: 'Cắt ngọn sau 20-25 ngày trồng, để lại 5cm cho tái sinh. Có thể thu hoạch mỗi 10-15 ngày. Tốt nhất hái vào buổi sáng.'
  },
  {
    name_en: 'Lemongrass',
    name_vi: 'Sả',
    scientific_name: 'Cymbopogon citratus',
    category: 'vegetable',
    growing_season: 'year_round',
    typical_growth_days: 90,
    water_requirements: 'medium',
    climate_zone: 'tropical, subtropical',
    common_pests: ['aphids', 'mealybug', 'scale insects'],
    common_diseases: ['rust', 'leaf spot'],
    planting_tips_en: 'Plant divisions or rooted stalks 50-60cm apart. Prefers full sun and well-drained soil. Water regularly during establishment. Divide clumps every 2-3 years.',
    planting_tips_vi: 'Trồng chồi hoặc cây có rễ cách nhau 50-60cm. Thích ánh sáng đầy đủ và đất thoát nước tốt. Tưới đều đặn khi còn nhỏ. Chia bụi mỗi 2-3 năm.',
    harvest_tips_en: 'Cut stalks at base when 30cm tall and 1.5cm thick. Can harvest year-round from mature clumps. Use fresh or dry for storage.',
    harvest_tips_vi: 'Cắt cây ở gốc khi cao 30cm và dày 1.5cm. Có thể thu hoạch quanh năm từ bụi trưởng thành. Dùng tươi hoặc phơi khô bảo quản.'
  },
  {
    name_en: 'Coconut',
    name_vi: 'Dừa',
    scientific_name: 'Cocos nucifera',
    category: 'fruit',
    growing_season: 'year_round',
    typical_growth_days: 365,
    water_requirements: 'medium',
    climate_zone: 'tropical',
    common_pests: ['rhinoceros beetle', 'red palm weevil', 'coconut scale'],
    common_diseases: ['bud rot', 'stem bleeding', 'root wilt'],
    planting_tips_en: 'Plant pre-germinated nuts in pits 1m x 1m x 1m, 7-9m apart. Requires coastal or well-drained soil. Apply organic manure and balanced fertilizer annually. Productive after 5-7 years.',
    planting_tips_vi: 'Trồng trái đã nảy mầm trong hố 1m x 1m x 1m, cách nhau 7-9m. Cần đất ven biển hoặc thoát nước tốt. Bón phân hữu cơ và phân cân đối hàng năm. Cho quả sau 5-7 năm.',
    harvest_tips_en: 'Harvest young nuts at 6-7 months for water, or mature nuts at 12 months for copra. Can produce 50-200 nuts/year. Productive for 60-80 years.',
    harvest_tips_vi: 'Hái trái non 6-7 tháng tuổi để uống nước, hoặc trái già 12 tháng để lấy cơm. Có thể cho 50-200 trái/năm. Cho quả được 60-80 năm.'
  },
  {
    name_en: 'Durian',
    name_vi: 'Sầu riêng',
    scientific_name: 'Durio zibethinus',
    category: 'fruit',
    growing_season: 'year_round',
    typical_growth_days: 120,
    water_requirements: 'high',
    climate_zone: 'tropical',
    common_pests: ['stem borer', 'fruit borer', 'fruit fly'],
    common_diseases: ['phytophthora', 'root rot', 'anthracnose'],
    planting_tips_en: 'Plant grafted trees 10-12m apart in deep, well-drained soil. Requires high rainfall and humidity. Mulch heavily. Apply organic fertilizer 3-4 times yearly. Can fruit after 4-5 years.',
    planting_tips_vi: 'Trồng cây ghép cách nhau 10-12m trong đất sâu, thoát nước tốt. Cần lượng mưa và độ ẩm cao. Phủ rơm dày. Bón phân hữu cơ 3-4 lần/năm. Có thể ra quả sau 4-5 năm.',
    harvest_tips_en: 'Fruit falls when ripe, or pick when stem cracks appear. Handle carefully. Best consumed within 2-3 days. Peak season June-August.',
    harvest_tips_vi: 'Quả rụng khi chín, hoặc hái khi có vết nứt ở cuống. Xử lý cẩn thận. Tốt nhất ăn trong vòng 2-3 ngày. Mùa cao điểm tháng 6-8.'
  },
  {
    name_en: 'Jackfruit',
    name_vi: 'Mít',
    scientific_name: 'Artocarpus heterophyllus',
    category: 'fruit',
    growing_season: 'year_round',
    typical_growth_days: 150,
    water_requirements: 'medium',
    climate_zone: 'tropical',
    common_pests: ['fruit borer', 'shoot borer', 'mealybug'],
    common_diseases: ['rhizopus rot', 'fruit rot', 'dieback'],
    planting_tips_en: 'Plant grafted trees 10-12m apart. Tolerates variety of soils but prefers well-drained. Water during dry season. Apply balanced fertilizer 2-3 times yearly. Can fruit after 3-4 years.',
    planting_tips_vi: 'Trồng cây ghép cách nhau 10-12m. Chịu được nhiều loại đất nhưng thích đất thoát nước tốt. Tưới khi khô hạn. Bón phân cân đối 2-3 lần/năm. Có thể ra quả sau 3-4 năm.',
    harvest_tips_en: 'Harvest when spines flatten and fruit emits strong aroma. Tap fruit - dull sound indicates ripeness. Can be eaten fresh or processed.',
    harvest_tips_vi: 'Thu hoạch khi gai xẹp và quả có mùi thơm mạnh. Gõ quả - âm thanh đục chỉ quả chín. Có thể ăn tươi hoặc chế biến.'
  },
  {
    name_en: 'Pomelo',
    name_vi: 'Bưởi',
    scientific_name: 'Citrus maxima',
    category: 'fruit',
    growing_season: 'year_round',
    typical_growth_days: 210,
    water_requirements: 'medium',
    climate_zone: 'tropical, subtropical',
    common_pests: ['citrus psyllid', 'leaf miner', 'scale insects', 'fruit fly'],
    common_diseases: ['greening disease', 'canker', 'gummosis'],
    planting_tips_en: 'Plant grafted trees 5-6m apart in well-drained soil. Water regularly but avoid waterlogging. Prune to maintain shape. Apply balanced fertilizer 4-6 times yearly. Can fruit after 3-4 years.',
    planting_tips_vi: 'Trồng cây ghép cách nhau 5-6m trong đất thoát nước tốt. Tưới đều đặn nhưng tránh úng. Tỉa cành giữ dáng. Bón phân cân đối 4-6 lần/năm. Có thể ra quả sau 3-4 years.',
    harvest_tips_en: 'Harvest when fruit is fully colored and slightly soft at stem end. Peak season September-December. Can store for several weeks in cool conditions.',
    harvest_tips_vi: 'Thu hoạch khi quả chuyển màu hoàn toàn và hơi mềm ở đầu cuống. Mùa cao điểm tháng 9-12. Có thể bảo quản vài tuần ở nơi mát.'
  },
  {
    name_en: 'Guava',
    name_vi: 'Ổi',
    scientific_name: 'Psidium guajava',
    category: 'fruit',
    growing_season: 'year_round',
    typical_growth_days: 120,
    water_requirements: 'medium',
    climate_zone: 'tropical, subtropical',
    common_pests: ['fruit fly', 'scale insects', 'mealybug'],
    common_diseases: ['wilt', 'canker', 'fruit rot'],
    planting_tips_en: 'Plant grafted or seedling trees 5-6m apart. Adapts to various soils. Prune after harvest to maintain shape and size. Apply balanced fertilizer 3-4 times yearly. Can fruit year-round.',
    planting_tips_vi: 'Trồng cây ghép hoặc cây giống cách nhau 5-6m. Thích nghi với nhiều loại đất. Tỉa sau thu hoạch để giữ dáng và kích thước. Bón phân cân đối 3-4 lần/năm. Có thể ra quả quanh năm.',
    harvest_tips_en: 'Pick when fruit changes from dark to light green and softens slightly. Can ripen at room temperature. Handle carefully to avoid bruising.',
    harvest_tips_vi: 'Hái khi quả chuyển từ xanh đậm sang xanh nhạt và hơi mềm. Có thể chín ở nhiệt độ phòng. Xử lý cẩn thận tránh dập.'
  }
];
